* Author: Nihanth
* Date Created: 02 May 2016
* Environment
  - OS: Windows 7, Ubuntu-16.04,Centos-6
  - Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
  - Bandwidth : 100Mbps
  - Hardware Configuration:8GBRAM , 
  - Processor:i5
  - Data : a5,@#$,-5a

* Objective
  - To simulate the Parasitoid-Host Dynamics experiment

* Pre conditions
  - Refer to first test case [[https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au/blob/master/test-cases/integration_test-cases/Parasitoid Host Dynamics/Parasitoid Host Dynamics_01_Usability_smk.org][Parasitoid Host Dynamics_01_Usability_smk.org]]

* Post conditions
  - Nil
* Test Steps
  1. Click on the simulation link 
  2. It should re-direct to the simulation page
  3. Click on the simulator link 
  4. A new tab will be opened with simulation proces
  5. Select Nicholson-Bailey Model present in the variables box and click on it
  6. Enter invalid values in Initial population of host (Ht),Initial population of female parasitoids (Pt),Reproductive rate of host without parasitism (Rm),Searching efficiency of parasitoid (a), and Avg no. of female parasitoids produced from each host (c) fields.
  7. Select Host DensityModel present in the variables box and click on it
  8. Enter invalid values in Initial population of host (Ht),Initial population of female parasitoids (Pt),Reproductive rate of host without parasitism (Rm),Searching efficiency of parasitoid (a),Avg no. of female parasitoids produced from each host (c) and Carrying capacity of host (K) fields.
  9. Select Nicholson-Bailey Model present in the variables box and click on it
  10. Enter invalid values in Initial population of host (Ht),Initial population of female parasitoids (Pt),Reproductive rate of host without parasitism (Rm),Searching efficiency of parasitoid (a),Avg no. of female parasitoids produced from each host (c),Clumping factor (k) fields.
  11. Select Comparison of Poisson and Negative Binomial Distribution Model present in the variables box and click on it
  12. Enter invalid values in the Initial population of female parasitoids (Pt,Searching efficiency of parasitoid (a) and Clumping factor (k) and click on the plot graph.
  13. To restart the simulation process click on the reset button.

* Expected result
  1. Simulation page should be opened
  2. A simulator link should be present
  3. Content should be present with no distortions and Junk charactersthe 
  4. An error message should be displayed on the screen
  5. It should redirect to the intial page

* Review/comments


